title: Grant Trowbridge's Blog
email: 
description: >
  A Cyber Security blog covering security-related topics, CTFs, and signals
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grant-trowbridge.github.io/" # the base hostname & protocol for your site
postCount: 5 # the number of posts on the "index" page

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink   : /:year/:title/
source: ./
destination: ./_site

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
